#! /usr/bin/env bash
host=${1-vm}
path=${2-/root/myapp}
# if [ -e ".gitignore" ]; then
set -ex
/usr/bin/rsync -avz --delete --exclude-from=$(pwd)/.gitignore root@${host}:${path}/ .
# else
# set -ex
# shellcheck disable=SC2086
# /usr/bin/rsync -avz --delete root@${host}:${path}/ .
# fi
