#!/usr/bin/env python3
import os
import shlex
import sys

from trans_image_name import trans_image

docker_bin = '/opt/homebrew/bin/docker'

cmds = [docker_bin]

for item in sys.argv[1:]:
    cmds.append(trans_image(item))
if sys.argv[1] in ['run', 'pull', 'rmi', 'rm']:
    print("➡️ ➡️ ➡️ ➡️", cmds, flush=True)
os.system(" ".join(shlex.quote(x) for x in cmds))


def run_realtime_raw(cmd):
    import subprocess, sys

    p = subprocess.Popen(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        bufsize=0
    )

    while True:
        chunk = p.stdout.read(1)
        if not chunk:
            break
        sys.stdout.write(chunk.decode(errors="ignore"))
        sys.stdout.flush()

    return p.wait()
