kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# containerdConfigPatches:
# - | 
#   [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.cn-hangzhou.aliyuncs.com"]
#     endpoint = ["http://registry.cn-hangzhou.aliyuncs.com:443"]
#   [plugins."io.containerd.grpc.v1.cri".registry.configs."registry.cn-hangzhou.aliyuncs.com".tls]
#     insecure_skip_verify = true
  
# networking:
#   disableDefaultCNI: true
# featureGates:
# "EphemeralContainers": true
nodes:
- role: control-plane
  extraPortMappings:
    - containerPort: 31256
      hostPort: 31256
      protocol: TCP
  kubeadmConfigPatches: 
  - |
    kind: ClusterConfiguration
    apiServer:
        extraArgs:
          audit-log-path: /var/log/kubernetes/kube-apiserver-audit.log
          audit-policy-file: /etc/kubernetes/policies/audit-policy.yaml
        extraVolumes:
          - name: audit-policies
            hostPath: /etc/kubernetes/policies
            mountPath: /etc/kubernetes/policies
            readOnly: true
            pathType: "DirectoryOrCreate"
          - name: "audit-logs"
            hostPath: "/var/log/kubernetes"
            mountPath: "/var/log/kubernetes"
            readOnly: false
            pathType: DirectoryOrCreate
  extraMounts:
    # - hostPath: /Users/acejilam/data/plugins/bin
    #   containerPath: /opt/cni/bin
    # - hostPath: /Users/acejilam/data/nfs
    #   containerPath: /nfs
    # - hostPath: /Users/acejilam/data/trace
    #   containerPath: /trace
    - hostPath: /Users/acejilam/script/audit-policy.yaml
      containerPath: /etc/kubernetes/policies/audit-policy.yaml
      readOnly: true
    - hostPath: /Users/acejilam/data/kind/logs
      containerPath: /var/log/kubernetes
      readOnly: false

- role: worker
  labels:
     node.kubernetes.io/instance-type: controlpanel
     topology.kubernetes.io/zone: zone-a
     nfs: true
     node: zone-a
  extraMounts:
  #   - hostPath: /Users/acejilam/data/plugins/bin
  #      containerPath: /opt/cni/bin
  #    - hostPath: /Users/acejilam/data/build_cache
  #      containerPath: /tmp/build_cache
  #    - hostPath: /Users/acejilam/data/nfs
  #      containerPath: /nfs
  #    - hostPath: /Users/acejilam/data/trace
  #      containerPath: /trace
- role: worker
  labels:
     node.kubernetes.io/instance-type: controlpanel
     topology.kubernetes.io/zone: zone-a
     node: zone-b
  extraMounts:
    # - hostPath: /Users/acejilam/data/plugins/bin
    #   containerPath: /opt/cni/bin
# kubeadmConfigPatches:
#   - |
#     kind: ClusterConfiguration
#     etcd:
#       local:
#         dataDir: /tmp/etcd # /tmp directory is a tmpfs(in memory),use it for speeding up etcd and lower disk IO.
#     apiServer:
#       certSANs:
#         - 127.0.0.1
#         - localhost
#       # extraEnvs:
#       #   - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
#       #     value: http://10.230.205.190:5080/api/default/traces
#       #   - name: OTEL_EXPORTER_OTLP_TRACES_HEADERS
#       #     value: Authorization='Basic cm9vdEBleGFtcGxlLmNvbTpmcHp4cTIwWWtPVXVWUG1r'
#       extraArgs:
#         # enable-admission-plugins: OwnerReferencesPermissionEnforcement,PodNodeSelector,PodTolerationRestriction,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
#         # feature-gates: APIServerTracing=true
#         # tracing-config-file: /trace/kube-apiserver.tracing
#   - |
#     apiVersion: kubeadm.k8s.io/v1beta4
#     kind: InitConfiguration
#     nodeRegistration:
#       kubeletExtraArgs:
#         cgroup-root: "/"
#         feature-gates: KubeletTracing=true
#   - |
#     apiVersion: kubeadm.k8s.io/v1beta4
#     kind: KubeletConfiguration
#     # environment:
#     # - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://10.230.205.190:5080/api/default/traces
#     # - OTEL_EXPORTER_OTLP_TRACES_HEADERS=Authorization='Basic cm9vdEBleGFtcGxlLmNvbTpmcHp4cTIwWWtPVXVWUG1r'
#     cgroupRoot: /
#     #tracing:
#     # endpoint:
#     # samplingRatePerMillion:
