#! /usr/bin/env bash
host=${1-vm}
path=${2-/root/myapp}
user=${3-root}

if [ -e ".gitignore" ]; then
    set -ex
	/usr/bin/rsync -aP --delete --exclude-from=.gitignore . ${user}@${host}:${path}
else
    set -ex
    /usr/bin/rsync -aP --delete . ${user}@${host}:${path}
fi
