#! /usr/bin/env bash
host=${1-vm}
path=${2-/root/myapp}
user=${3-root}

cmd=""
# 检查远端是否存在 .git 目录
if ssh "${user}@${host}" "[ -d '${path}/.git' ]"; then
	if [ -e ".gitignore" ]; then
		cmd="/usr/bin/rsync -avzP --delete --exclude=.git --exclude-from=.gitignore . ${user}@${host}:${path}"
	else
		cmd="/usr/bin/rsync -avzP --delete --exclude=.git . ${user}@${host}:${path}"
	fi
else
	if [ -e ".gitignore" ]; then
		cmd="/usr/bin/rsync -avzP --delete --exclude-from=.gitignore . ${user}@${host}:${path}"
	else
		cmd="/usr/bin/rsync -avzP --delete . ${user}@${host}:${path}"
	fi
fi
set -x
eval "${cmd}"
