name: Sync-To-Gitee

on:
  push:
    branches:
      - main

jobs:
  push-to-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Push to Gitee
        run: |
          remote_repo="https://${GITEE_USERNAME}:${GITEE_PASSWORD}@gitee.com/ls-2018/script.git"
          git config --global --add safe.directory `pwd`
          git remote add gitee "${remote_repo}"
          git show-ref # useful for debugging
          git branch --verbose
          # publish all
          git push --force gitee
          git push --all --force gitee
          git push --tags --force gitee
        env:
          GITEE_USERNAME: ${{ secrets.GITEE_USERNAME }}
          GITEE_PASSWORD: ${{ secrets.GITEE_PASSWORD }}
